import dash_html_components as html

poetry = [
    {
        "title": [
            html.H6("The blur in my vision"),
            html.H6("has ceased to exist")
            ],
        "body": 
            [
            html.P("Oh, my dear, now I see."),
            html.P("Yes, we weren't meant to be."),
            html.P("It has been a while,"),
            html.P("and my thoughts"),
            html.P("are finally clear."),
            html.Br(),
            html.P("We had tangled our hearts"),
            html.P("into powerful alchemy,"),
            html.P("we've had lost who we were"),
            html.P("and what we stand for."),
            html.Br(),
            html.P("That was no way to live."),
            html.Br(),
            html.P("We needed no sleep,"),
            html.P("and every day was perfect,"),
            html.P("even though"),
            html.P("we both know they weren't."),
            html.Br(),
            html.P("I still smoke my late cigarettes,"),
            html.P("some of them still wonder"),
            html.P("where you are"),
            html.P("and"),
            html.P("how you've been."),
            html.Br(),
            html.P("They already know"),
            html.P("I had lost myself."),
            html.P("I still haven't brought up the courage to tell them"),
            html.Br(),
            html.P("I've lost you."),
        ],
        "day": 8765,
        "date": "03/06/2021"
    },
    
    {
        "title": html.H6("Uma homenagem ao Limbo"),
        "body": 
            [
            html.P("Eu e os cigarros conversamos um pouco,"),
            html.P("e decidimos seguir caminhos diferentes."),
            html.Br(),
            html.P("Estou construindo uma torre,"),
            html.P("isso me lembra de um lugar antigo."),
            html.Br(),
            html.P("As paredes não falam mais."),
            html.Br(),
            html.P("Ontem, pedi informações a um demônio."),
            html.P("Ninguém sabe mais onde fica a velha torre."),
            html.Br(),
            html.P("Não sabendo como percorrer esses caminhos,"),
            html.P("Eu me ajoelho e oro. Há ferrugem na minha armadura,"),
            html.P("e eu não vejo ela há muito tempo."),
            html.Br(),
            html.P("O vazio, a vastidão."),
            html.P("Eles engolem minhas orações, cada palavra reverbera."),
            html.Br(),
            html.P("Esses cães famintos não têm maneiras,"),
            html.P("tenho pena deles por meus próprios erros."),
            html.Br(),
            html.P("Eu não posso mais cuidar deles."),
            html.Br(),
            html.P("E então escrevo aqui minha última pequena nota."),
            html.P("E então eu deixo este lugar."),
            html.Br(),
            html.P("Este não é meu reino, aqueles não são meus templos."),
            html.P("O deserto está cheio de relíquias e ruínas,"),
            html.P("é minha hora de sucumbir."),
            html.Br(),
            html.P("Com certeza este deserto brilhará novamente."),
            html.P("Meus velhos amigos, espero que um dia possamos nos reunir."),
        ],
        "day": 8532,
        "date": "13/10/2020"
    },
    
    {
        "title": html.H6("Ode ao canto"),
        "body": 
            [
            html.P("Voice no longer"),
            html.P("resonates mind."),
            html.Br(),
            html.P("Crumbling paths don't"),
            html.P("allow a peaceful return."),
            html.Br(),
            html.P("Being faithful to unconsidered premises"),
            html.P("I've walked a thousand miles forward,"),
            html.P("only to find myself two thousand miles back."),
            html.Br(),
            html.P("Poetry is passion of vanity."),
            html.P("And vanity is all there is."),
            html.Hr(),
            html.P("Não há explicação para coisa alguma."),
            html.P("Entretanto ainda contamos estórias."),
            html.P("Somos estórias, porém não existe livro."),
            html.Br(),
            html.P("E cada dia mil estórias acabam,"),
            html.P("não são páginas fechadas."),
            html.Hr(),
            html.P("We have laughed and we have cried,"),
            html.P("otherwise we wouldn't be."),
            html.P("Or is it not so?"),
            html.Br(),
            html.P("I lay down, there is no roof nor floor."),
            html.P("I fly and I fall, and it is all the same."),
            html.P("But the walls are always there,"),
            html.P("we paint it with our horizons, it changes as the story goes."),
            html.Hr(),
            html.P("Queria eu fechar estas janelas,"),
            html.P("e finalizar o canto sem desespero nem alegria."),
            html.P("Mas não há nada mais além do canto."),
            html.P("E aí está a poesia."),
        ],
        "day": 8023,
        "date": "23/05/2019"
    },
    
    {
        "title": html.H6("0"),
        "body": 
            [
            html.P("Soldados marcham,"),
            html.P("engrenagens giram."),
            html.Br(),
            html.P("Atam-se gravatas,"),
            html.P("partem-se corações."),
            html.Br(),
            html.P("Há devaneios."),
            html.P("Há consumo."),
            html.Br(),
            html.P("Alguns preferem virar pó"),
            html.P("à virar alimento,"),
            html.P("lentamente:"),
            html.P("abaixo de todo chão;"),
            html.P("de toda esperança."),
            html.Br(),
            html.P("Quando a engrenagem quebra,"),
            html.P("substitui-se,"),
            html.P("e tão é assim"),
            html.P("a vida."),
        ],
        "day": 7844,
        "date": "25/11/2018"
    },
    
    {
        "title": html.H6("0"),
        "body": 
            [
            html.P("Not able to see luxury on the simple things,"),
            html.P("I am a fool"),
            html.P("and I have been fooled."),
            html.Br(),
            html.P("How could I ever see,"),
            html.P("in the light,"),
            html.P("only void?"),
            html.Br(),
            html.P("Where are the colors which one day"),
            html.P("will represent beauty?"),
            html.Br(),
            html.P("What are the sounds that sustain,"),
            html.P("in its brilliance,"),
            html.P("only pain?"),
            html.Hr(),
            html.P("Oh I have not been with the gods"),
            html.P("to elucidate it,"),
            html.P("and so haven't you."),
            html.Br(),
            html.P("There is no resentment"),
            html.P("into which I could crawl."),
            html.Br(),
            html.P("The roots and the vines,"),
            html.P("they grow, but they also"),
            html.P("perish."),
            html.Br(),
            html.P("We are all falling,"),
            html.P("so we pray for wings."),
            html.Br(),
            html.P("we never think"),
            html.P("there may be no ground beneath."),
        ],
        "day": 7741,
        "date": "14/08/2018"
    }
]
    
    




