import dash_html_components as html

poetry = [
    {
        "title": [
            html.H6("The blur in my vision"),
            html.H6("has ceased to exist")
            ],
        "body": 
            [
            html.P("Oh, my dear, now I see."),
            html.P("Yes, we weren't meant to be."),
            html.P("It has been a while,"),
            html.P("and my thoughts"),
            html.P("are finally clear."),
            html.Br(),
            html.P("We had tangled our hearts"),
            html.P("into powerful alchemy,"),
            html.P("we've had lost who we were"),
            html.P("and what we stand for."),
            html.Br(),
            html.P("That was no way to live."),
            html.Br(),
            html.P("We needed no sleep,"),
            html.P("and every day was perfect,"),
            html.P("even though"),
            html.P("we both know they weren't."),
            html.Br(),
            html.P("I still smoke my late cigarettes,"),
            html.P("some of them still wonder"),
            html.P("where you are"),
            html.P("and"),
            html.P("how you've been."),
            html.Br(),
            html.P("They already know"),
            html.P("I had lost myself."),
            html.P("I still haven't brought up the courage to tell them"),
            html.Br(),
            html.P("I've lost you."),
        ],
        "day": 8765,
        "date": "03/06/2021"
    },
    
    {
        "title": html.H6("Uma homenagem ao Limbo"),
        "body": 
            [
            html.P("Eu e os cigarros conversamos um pouco,"),
            html.P("e decidimos seguir caminhos diferentes."),
            html.Br(),
            html.P("Estou construindo uma torre,"),
            html.P("isso me lembra de um lugar antigo."),
            html.Br(),
            html.P("As paredes não falam mais."),
            html.Br(),
            html.P("Ontem, pedi informações a um demônio."),
            html.P("Ninguém sabe mais onde fica a velha torre."),
            html.Br(),
            html.P("Não sabendo como percorrer esses caminhos,"),
            html.P("Eu me ajoelho e oro. Há ferrugem na minha armadura,"),
            html.P("e eu não vejo ela há muito tempo."),
            html.Br(),
            html.P("O vazio, a vastidão."),
            html.P("Eles engolem minhas orações, cada palavra reverbera."),
            html.Br(),
            html.P("Esses cães famintos não têm maneiras,"),
            html.P("tenho pena deles por meus próprios erros."),
            html.Br(),
            html.P("Eu não posso mais cuidar deles."),
            html.Br(),
            html.P("E então escrevo aqui minha última pequena nota."),
            html.P("E então eu deixo este lugar."),
            html.Br(),
            html.P("Este não é meu reino, aqueles não são meus templos."),
            html.P("O deserto está cheio de relíquias e ruínas,"),
            html.P("é minha hora de sucumbir."),
            html.Br(),
            html.P("Com certeza este deserto brilhará novamente."),
            html.P("Meus velhos amigos, espero que um dia possamos nos reunir."),
        ],
        "day": 8532,
        "date": "13/10/2020"
    },
    
    {
        "title": html.H6("Ode ao canto"),
        "body": 
            [
            html.P("Voice no longer"),
            html.P("resonates mind."),
            html.Br(),
            html.P("Crumbling paths don't"),
            html.P("allow a peaceful return."),
            html.Br(),
            html.P("Being faithful to unconsidered premises"),
            html.P("I've walked a thousand miles forward,"),
            html.P("only to find myself two thousand miles back."),
            html.Br(),
            html.P("Poetry is passion of vanity."),
            html.P("And vanity is all there is."),
            html.Hr(),
            html.P("Não há explicação para coisa alguma."),
            html.P("Entretanto ainda contamos estórias."),
            html.P("Somos estórias, porém não existe livro."),
            html.Br(),
            html.P("E cada dia mil estórias acabam,"),
            html.P("não são páginas fechadas."),
            html.Hr(),
            html.P("We have laughed and we have cried,"),
            html.P("otherwise we wouldn't be."),
            html.P("Or is it not so?"),
            html.Br(),
            html.P("I lay down, there is no roof nor floor."),
            html.P("I fly and I fall, and it is all the same."),
            html.P("But the walls are always there,"),
            html.P("we paint it with our horizons, it changes as the story goes."),
            html.Hr(),
            html.P("Queria eu fechar estas janelas,"),
            html.P("e finalizar o canto sem desespero nem alegria."),
            html.P("Mas não há nada mais além do canto."),
            html.P("E aí está a poesia."),
        ],
        "day": 8023,
        "date": "23/05/2019"
    },
    
    {
        "title": html.H6("0"),
        "body": 
            [
            html.P("Soldados marcham,"),
            html.P("engrenagens giram."),
            html.Br(),
            html.P("Atam-se gravatas,"),
            html.P("partem-se corações."),
            html.Br(),
            html.P("Há devaneios."),
            html.P("Há consumo."),
            html.Br(),
            html.P("Alguns preferem virar pó"),
            html.P("à virar alimento,"),
            html.P("lentamente:"),
            html.P("abaixo de todo chão;"),
            html.P("de toda esperança."),
            html.Br(),
            html.P("Quando a engrenagem quebra,"),
            html.P("substitui-se,"),
            html.P("e tão é assim"),
            html.P("a vida."),
        ],
        "day": 7844,
        "date": "25/11/2018"
    },
    
    {
        "title": html.H6("0"),
        "body": 
            [
            html.P("Not able to see luxury on the simple things,"),
            html.P("I am a fool"),
            html.P("and I have been fooled."),
            html.Br(),
            html.P("How could I ever see,"),
            html.P("in the light,"),
            html.P("only void?"),
            html.Br(),
            html.P("Where are the colors which one day"),
            html.P("will represent beauty?"),
            html.Br(),
            html.P("What are the sounds that sustain,"),
            html.P("in its brilliance,"),
            html.P("only pain?"),
            html.Hr(),
            html.P("Oh I have not been with the gods"),
            html.P("to elucidate it,"),
            html.P("and so haven't you."),
            html.Br(),
            html.P("There is no resentment"),
            html.P("into which I could crawl."),
            html.Br(),
            html.P("The roots and the vines,"),
            html.P("they grow, but they also"),
            html.P("perish."),
            html.Br(),
            html.P("We are all falling,"),
            html.P("so we pray for wings."),
            html.Br(),
            html.P("We never think"),
            html.P("there may be no ground beneath."),
        ],
        "day": 7741,
        "date": "14/08/2018"
    },
    
    {
        "title": html.H6("0"),
        "body": 
            [
            html.P("Tenho fome"),
            html.P("e não sinto mais"),
            html.P("o gosto."),
            html.Br(),
            html.P("Como eu odeio"),
            html.P("estas janelas."),
            html.P("À tudo, o meu ódio."),
            html.Br(),
            html.P("Sei que há"),
            html.P("alguns galhos de árvore por ai"),
            html.P("que eu não odeio."),
            html.Br(),
            html.P("Pelo contrário,"),
            html.P("eu os amo."),
            html.Br(),
            html.P("Houve a época em que minha melhor amiga"),
            html.P("era uma casa abandonada."),
            html.P("Eu via ela todo dia, pela janela."),
            html.Br(),
            html.P("Hoje as janelas me proporcionam vidas."),
            html.P("Aquários, e peixes comportados."),
            html.Br(),
            html.P("O zen budista diz que a"),
            html.P("vida sempre poderá lhe prover dor,"),
            html.P("mas só você pode afligi-la a si mesmo."),
            html.Br(),
            html.P("Tudo isso é uma grande bobagem niilista."),
            html.P("Foi ai que eu perdi o gosto;"),
            html.P("o apetite ainda me assombra."),
            html.Br(),
            html.P("Eu não odeio estas janelas."),
        ],
        "day": 7723,
        "date": "27/07/2018"
    },
    
    {
        "title": html.H6("0"),
        "body": 
            [
            html.P("There are black stains on my memories,"),
            html.P("of times I would not want to forget."),
            html.Br(),
            html.P("As I walk forward,"),
            html.P("I feel neglected"),
            html.P("by my future self."),
            html.Br(),
            html.P("Every month or so,"),
            html.P("I move the furniture of my house,"),
            html.P("but I don't remember"),
            html.P("where things once were."),
            html.Br(),
            html.P("As I walk my dog,"),
            html.P("I ask myself:"),
            html.P("Will I also forget these moments"),
            html.P("when time has passed?"),
            html.Br(),
            html.P("The songs are forgotten,"),
            html.P("the lines of an old book"),
            html.P("seem brand new."),
            html.Br(),
            html.P("I see old pictures and"),
            html.P("I talk to old friends."),
            html.P("What are you, face in the mirror?"),
            html.P("I have already forgotten"),
            html.Br(),
            html.P("When it's late and cold,"),
            html.P("I look at the sky,"),
            html.P("trying to remember some other day."),
            html.Br(),
            html.P("Little sand castle,"),
            html.P("did the wind visit you?"),
            html.P("Little paper tower,"),
            html.P("did I burn you?"),
            html.Br(),
            html.P("But there are far more"),
            html.P("dead branches in the ground"),
            html.P("than dead memories,"),
            html.P("dead thoughts."),
            html.Br(),
            html.P("And I am also to perish,"),
            html.P("not on pain or suffering,"),
            html.P("but only in vain."),
            html.Br(),
            html.P("Why"),
            html.P("Will you forget us all?"),
        ],
        "day": 7658,
        "date": "23/05/2018"
    },
    
    {
        "title": html.H6("kor nihil"),
        "body": 
            [
            html.P("Past selves left me to rot."),
            html.P("In this great decay, I've become devoted"),
            html.P("to the truth."),
            html.Br(),
            html.P("There's a god in my head and he yells at me,"),
            html.P("my thoughts are empty and my mind is weak."),
            html.Br(),
            html.P("In the midst of the steam of paranoia,"),
            html.P("I grew hatred, that's all I see."),
            html.Br(),
            html.P("Finally, I am nothing."),
            html.Hr(),
            html.P("My muscles are sore, and I spit blood on the toilet."),
            html.Br(),
            html.P("As time goes by, I lose certainty."),
            html.P("Mirror, I see no king, no man."),
            html.Br(),
            html.P("Are the demons haunting me?"),
            html.P("Or am I the one hunting them?"),
            html.Br(),
            html.P("I still ought to understand"),
            html.P("why the flowers are out there,"),
            html.P("and the birds chirp away."),
            html.Hr(),
            html.P("The mermaid swims,"),
            html.P("and I've become friends with"),
            html.P("fourteen gargoyles."),
            html.Br(),
            html.P("Afraid of swimming,"),
            html.P("I found myself blind."),
            html.Br(),
            html.P("Afraid of falling,"),
            html.P("I found myself deaf."),
            html.Br(),
            html.P("Finally, I am nothing."),
        ],
        "day": 7654,
        "date": "19/05/2018"
    },
    
    {
        "title": html.H6("Gut and furnace"),
        "body": 
            [
            html.P("4 PM, morning."),
            html.P("Gray sky fastens the indifference."),
            html.P("The songs are loud and complacent."),
            html.Br(),
            html.P("I light up the only cigarette of the day."),
            html.Br(),
            html.P("Those smirky eyes never lie."),
            html.Br(),
            html.P("In the bathroom,"),
            html.P("as I disgorge,"),
            html.P("they become delighted."),
            html.Br(),
            html.P("'We wait a thousand years and"),
            html.P("a thousand years more!"),
            html.P("We watch the pitiful,"),
            html.P("the cherishable."),
            html.Br(),
            html.P("Sir, bring us more!"),
            html.P("One pesky demon - to bother lightly."),
            html.P("An elder woman - to listen and laugh!"),
            html.P("And welcome all those marvelous creatures outside,"),
            html.P("they shall be here too."),
            html.Br(),
            html.P("Bring everyone,"),
            html.P("let's all watch,"),
            html.P("as this little creature "),
            html.P("gives us a place to dance,"),
            html.P("laugh and sing.'"),
            html.Br(),
            html.P("They dance around my recycled coffee."),
            html.P("My recycled hatred."),
            html.Br(),
            html.P("I flush the demons and wash my hands and face."),
            html.P("Red eyes,"),
            html.P("I'm smeared with blood clots."),
            html.Br(),
            html.P("Oh, just laugh and sing."),
            html.P("Laugh and sing."),
        ],
        "day": 7605,
        "date": "31/03/2018"
    },
    
    {
        "title": html.H6("Temperature"),
        "body": 
            [
            html.P("I sit on the balcony and the fourth cigarette"),
            html.P("sends his last regards.  "),
            html.P("Cold,"),
            html.P("the demons ought to whisper"),
            html.P("today."),
            html.P("Am I willing to hear from them?"),
            html.Br(),
            html.P("4 AM,"),
            html.P("I lay naked in the bathtub,"),
            html.P("the water drips away."),
            html.P("There's a subtle feeling of disregard."),
            html.Br(),
            html.P("With closed windows,"),
            html.P("the bathroom only resembles what eyes see when shut."),
            html.P("There's an agonizing tremble."),
            html.P("In all directions, "),
            html.P("my eyes are shut."),
            html.P("Is it all nothing?"),
            html.Br(),
            html.P("I dry myself out."),
            html.P("Warm clothes."),
            html.Br(),
            html.P("I sleep,"),
            html.P("to soon be awake again."),
            html.Br(),
            html.P("Is it all enough?"),
            html.P("My paranoia left the real world,"),
            html.P("only to settle itself on my dreams."),
            html.P("There, all I see is against me."),
            html.Br(),
            html.P("My throat burns,"),
            html.P("the smoke lurks around,"),
            html.P("the coffee mug heats my hatred."),
            html.P("I jump off the roof, "),      
            html.P("the abyss seems to never end."),
            html.P("Again, I close my eyes."),
            html.P("I submerge into the black pool of hot coffee."),
            html.Br(),
            html.P("The creatures swim around."),
            html.P("They yell."),
            html.P("They cherish me."),
            html.P("I know their reasons."),
            html.Br(),
            html.P("In the very end, will we all emerge as friends?"),
            html.Br(),
            html.P("They are hungry, I am thirsty."),
            html.P("Who is consuming who?"),
            html.Br(),
            html.P("I open my eyes."),
            html.P("The coffee is gone, as so is the creatures."),
            html.Br(),
            html.P("I win another day?"),
            html.P("Now I wait, as I know"),
            html.P("they will soon"),
            html.P("whisper again."),
        ],
        "day": 7601,
        "date": "27/03/2018"
    },
]
    
    




